# -*- coding: utf-8 -*-
"""AREARECTANGULO.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JL47mU5JhUQRp4ofqNv_Xq6rtmVyrGDw
"""

def calcular_area(base, altura):
  return base * altura
base = float(input("ingrese la base: "))
altura = float(input("ingrese la altura: "))

area = calcular_area(base, altura)
print(f"El área del rectángulo es: {area}")