# -*- coding: utf-8 -*-
"""contador

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4Avy5Tr4bt0nt4EGau6lqmgmIXcrJIt
"""

contador = 0  # variable global

def incrementar():
    global contador
    local = 5  # variable local
    contador += local
    print(f"Contador actual: {contador}")

incrementar()
incrementar()
incrementar()